services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard-peer
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  example-http-server:
    image: python:3
    container_name: http-vpn
    network_mode: service:wireguard
    command: python -m http.server 8080 --bind 0.0.0.0
    volumes:
      - ./html:/html
    working_dir: /html
    depends_on:
      - wireguard
    restart: unless-stopped